concurrency:
  group: ${{ github.workflow }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - uses: ./.github/actions/prepare
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - run: pnpm build
      - run: npx should-semantic-release --verbose && npx release-it --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
